### ISSUE TITLE
Shouldn't mention in code block.

### ISSUE THREAD

**Issue by chunlea** [jekyll/jekyll-mentions#7] opened 2014-04-14 02:59 UTC
I found that jekyll-mentions turns such `@import` in code block to github users' link. It is annoying, right?

I think we need to add some roles to ignore some phrases like `@import`. I like mentions, but I don't want to destory my code block.

**Comment by davidcelis** [comment] 2015-04-12 01:33
Is this fixed in the version running on the `github-pages` gem? The issue is still present in the latest release of that...

**Comment by le717** [comment] 2015-04-24 19:37
@davidcelis No clue. jch/html-pipeline#163 was closed and I can't find any further discussion about fixing it. I just hit the same issue I reported in https://github.com/jekyll/jekyll-mentions/issues/7#issuecomment-64440939, but this time with an `@keyframes` rule.

**Comment by sandipb** [comment] 2015-05-14 23:22
This breaks code highlighting for me right now. Had to disable the plugin to make highlighting work.

This was breaking for me.

```liquid
{% highlight bash %}
$ echo hello > /dev/null
{% endhighlight %}
```

**Closed** 2016-03-08 23:15 UTC
