### ISSUE TITLE
Use jekyll-mentions will add extra meta header

### ISSUE THREAD

**Issue by crispgm** [jekyll/jekyll-mentions#37] opened 2016-07-18 16:42 UTC
Without jekyll-mentions:

```
<!DOCTYPE html>
<html>

  <head>
  <meta charset="utf-8">
```

With jekyll-mentions:

```
<!DOCTYPE html>                                                                                                                                                                   
<html>

  <head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <meta charset="utf-8">
```

I tried by creating a new project `jekyll new test`, barely the same outputs.

**Comment by parkr** [comment] 2016-07-19 23:55
Hey! Yeah, we noticed this too, sadly. It seems to come from the way nokogiri writes back documents. If this is missing, it adds it. Am I remembering right, @benbalter? I believe this is a duplicate of https://github.com/jekyll/jemoji/issues/41 then.

**Comment by pathawks** [comment] 2016-07-20 00:03
sparklemotion/nokogiri#1008

**Comment by 7php** [comment] 2017-07-18 07:22
I don't think this should be an issue, unless you are not using UTF-8, right?

**Comment by benbalter** [comment] 2017-07-18 14:11
The proposal there is to move to https://github.com/rubys/nokogumbo. We have a lot of history with nokogiri, and would suggest we evaluate performance, maintenance, and cross-platform compatibility if we're thinking about moving parsers.

**Comment by parkr** [comment] 2017-07-18 15:38
Moreover, `html-pipeline` is what we use here, so we don't actually own the logic (which is nice). If nokogumbo is a drop-in replacement (or close) and support could be added to html-pipeline, that would make our lives a lot easier.

**Closed** 2018-04-25 05:35 UTC
Labels: bug

**Comment by ashmaroli** [comment] 2018-04-25 08:55
@crispgm Why did you close this..? Has it been resolved `upstream` or on `master`?

**Comment by crispgm** [comment] 2018-04-25 10:48
@ashmaroli it's a common issue across Jekyll's repos and more. so i closed here.

**Comment by ashmaroli** [comment] 2018-04-25 10:51
okay.. I have PRs open proposing a fix if the issue is specific to just `jekyll-mentions` and `jemoji`..
